### ISSUE TITLE
Virtual Kubelet: Service Integration

### ISSUE THREAD

**Issue by MbolotSuse** [rancher/k3k#140]
Users of a Virtual Cluster will want to expose the pods of the cluster using services, like they can do with a full k8s cluster. Currently, only the pods are synchronized to the Host Cluster, so services have limited/no effect. To fix this, we need to evaluate the ways to synchronize services to the host cluster.

**Comment by enrichman** [comment]
@galal-hussein I think https://github.com/rancher/k3k/pull/154 is related.

**Comment by jp-gouin** [comment]
can we close this one ?

**Comment by galal-hussein** [comment]
yup closing this issue
