### ISSUE TITLE
Controller fails to create ingress

### ISSUE THREAD

**Issue by maxsokolovsky** [rancher/k3k#71]
When I create a cluster whose `expose` option is `ingress`, I pass it the `ingressClassName`. But the controller fails to create the ingress.
It cannot get the node address from the node object.

**Comment by galal-hussein** [comment]
Tested with: `v0.1.1-rc2`

Creating a cluster object with the name "system" will result in the following error message:
```
I0105 23:43:51.014334       1 cluster.go:145] enqueue cluster [system]
E0105 23:43:51.014341       1 cluster.go:184] Invalid cluster name system, no action will be taken
```

using the k3kcli with create cluster with name system will result in:
```
k3kcli-amd64 cluster create  --servers 1 --agents 0 --name system --token test
FATA[0000] invalid cluster name
``
